name: "Code Quality"
on: [ push, pull_request ]

jobs:
  CodeQuality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install shellcheck 0.8.0
        run: ./src/ci/install-shellcheck.sh

      - name: Install shellspec
        run: ./src/ci/install-shellspec.sh

      - name: before pr
        run: ./scripts/before-pr.sh

      - name: check for TODOs
        uses: tegonal/workflow-helper@v0.3.0
        with:
          commands: todo-checker
