name: Quality Assurance
on: [ push, pull_request ]

jobs:
  before_pr:
    name: before-pr.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install shellcheck
        run: ./src/ci/install-shellcheck.sh

      - name: Install shellspec
        run: ./src/ci/install-shellspec.sh

      - name: before-pr.sh
        run: ./scripts/before-pr.sh

  todo_checker:
    name: check for TODOs
    runs-on: ubuntu-latest
    steps:
      - name: check for TODOs
        uses: tegonal/workflow-helper@v0.3.0
        with:
          commands: todo-checker
